  server:
    port: 8081

  spring:
    application:
      name: user-service
    config:
      import: optional:file:.env[.properties]

    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}

    # ===== Database Configuration =====
    datasource:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:user_service}
      username: ${DB_USER}
      password: ${DB_PASSWORD}


    jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false
      show-sql: false
      properties:
        hibernate:
          format_sql: true

  # ===== JWT Configuration =====
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

  # ===== Secure =====
  encryption:
    token-secret: ${TOKEN_ENCRYPTION_KEY}

  internal:
    api:
      secret: ${INTERNAL_API_SECRET}

  oauth:
    frontend:
      redirect-uri: ${OAUTH_FRONTEND_REDIRECT_URI:http://localhost:5173/dashboard}
    http:
      connect-timeout: 5s
      read-timeout: 10s
    state:
      store: ${OAUTH_STATE_STORE:memory}
      ttl: 10m
    providers:
      spotify:
        client-id: ${SPOTIFY_CLIENT_ID:}
        client-secret: ${SPOTIFY_CLIENT_SECRET:}
        redirect-uri: ${SPOTIFY_REDIRECT_URI:http://127.0.0.1:8081/api/oauth/callback/spotify}
        auth-uri: https://accounts.spotify.com/authorize
        token-uri: https://accounts.spotify.com/api/token
        profile-uri: https://api.spotify.com/v1/me
        scopes:
          - user-read-private
          - playlist-read-private
          - playlist-read-collaborative
          - playlist-modify-private
          - playlist-modify-public
      youtube:
        client-id: ${YOUTUBE_CLIENT_ID:}
        client-secret: ${YOUTUBE_CLIENT_SECRET:}
        redirect-uri: ${YOUTUBE_REDIRECT_URI:http://127.0.0.1:8081/api/oauth/callback/youtube}
        auth-uri: https://accounts.google.com/o/oauth2/v2/auth
        token-uri: https://oauth2.googleapis.com/token
        profile-uri: https://openidconnect.googleapis.com/v1/userinfo
        scopes:
          - openid
          - https://www.googleapis.com/auth/youtube



  # ===== Logging =====
  logging:
    level:
      "ru.nsu.melody_shift": DEBUG
      "org.springframework.security": DEBUG
      "org.hibernate.SQL": WARN
