CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(20)              NOT NULL UNIQUE,
    email      VARCHAR(50)              NOT NULL UNIQUE,
    password   VARCHAR(255)             NOT NULL,
    enabled    BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE user_roles
(
    user_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role    VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, role)
);

CREATE TABLE oauth_connection
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT                   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    platform            VARCHAR(20)              NOT NULL,
    provider_account_id VARCHAR(255)             NOT NULL,
    access_token        TEXT                     NOT NULL,
    refresh_token       TEXT,
    expires_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    scopes              VARCHAR(500),
    status              VARCHAR(30)              NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (user_id, platform)
);
